# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
