# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='timestamp',
        ),
    ]
